a = input('Digite algo:')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É numérico?', a.isalnum())
print('É alfabético?', a.isalpha())
print('É alfaumérico?', a.isalnum())
print('Está em maiuscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())
