#não consegui
brasileirao = ('Flamengo', 'Atlético', 'São Paulo', 'Internacional', 'Grêmio', 'Palmeiras', 'Sport Recife', 'Cruzeiro', 'Botafogo', 'Corinthians', 'Vasco da Gama', 'Fluminense', 'América-MG', 'Chapecoense', 'Santos', 'EC Vitória', 'Bahia', 'Paraná', 'Atlético-PR', 'Ceará SC')
print('-='*200)
print(f'Lista dos times do Brasileirão: {brasileirao}')
print()
print('-='*200)
print(f'Os 5 primeiros colocados são: {brasileirao[:5]}')
print()
print('-='*200)
print(brasileirao[:-4])
print()
print('-='*200)
print(sorted(brasileirao))
print()
print('-='*200)
print(f'A Chapecoense está na {brasileirao[frase.find('Chapecoense')]} posição.')
